"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { courses, type CourseCategory } from "@/src/domain/course-catalog";

const labels: Record<string, string> = { Mathematiques: "Mathématiques", Francais: "Français", Anglais: "English", Sciences: "Sciences", Arabe: "Arabe", Coran: "Coran" };

export default function StudentCoursesPage() {
  const [filter, setFilter] = useState<"Toutes" | CourseCategory>("Toutes");
  const [query, setQuery] = useState("");
  const [locale, setLocale] = useState<"fr" | "en">("fr");
  const visible = useMemo(() => courses.filter((course) => (filter === "Toutes" || course.category === filter) && `${course.title} ${course.objective}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  const fr = locale === "fr";

  return <main className="student-v2-shell min-h-screen bg-[#f3faf5]"><aside className="student-v2-sidebar hidden lg:flex"><Link href="/" className="student-v2-logo"><img src="/ui/logo-madrasa-quebec.png" alt="Madrasa Québec Network" /></Link><span className="student-v2-label">{fr ? "Mon espace" : "My space"}</span><Link className="student-v2-nav" href="/student">☀ <span>{fr ? "Aujourd’hui" : "Today"}</span></Link><Link className="student-v2-nav active" href="/student/cours">▣ <span>{fr ? "Mes cours" : "My courses"}</span></Link><Link className="student-v2-nav" href="/student/jeux">🎮 <span>{fr ? "Jouer et apprendre" : "Play and learn"}</span></Link><Link className="student-v2-nav" href="/student/progression">✦ <span>{fr ? "Ma progression" : "My progress"}</span></Link></aside><section className="student-v2-main"><header className="student-v2-top"><div><p className="student-v2-kicker">{fr ? "Espace élève" : "Student space"}</p><h1>{fr ? "Mes cours" : "My courses"}</h1></div><button className="student-v2-locale" onClick={() => setLocale(fr ? "en" : "fr")}>{fr ? "EN" : "FR"}</button></header><section className="student-course-intro"><div><p className="student-v2-kicker">{fr ? "Choisis ton prochain défi" : "Choose your next challenge"}</p><h2>{fr ? "Apprendre peut changer de forme." : "Learning can take many forms."}</h2><p>{fr ? "Mathématiques, français, anglais, sciences, arabe ou Coran : avance à ton rythme." : "Math, French, English, science, Arabic or Quran: move at your own pace."}</p></div><div className="student-course-orbit"><span>∑</span><span>ABC</span><span>⌁</span><span>☽</span></div></section><div className="student-course-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={fr ? "Rechercher un cours…" : "Search a course…"} aria-label={fr ? "Rechercher un cours" : "Search a course"} /><div className="student-course-filters"><button className={filter === "Toutes" ? "active" : ""} onClick={() => setFilter("Toutes")}>{fr ? "Tout" : "All"}</button>{(["Mathematiques", "Francais", "Anglais", "Sciences", "Arabe", "Coran"] as CourseCategory[]).map((category) => <button key={category} className={filter === category ? "active" : ""} onClick={() => setFilter(category)}>{labels[category]}</button>)}</div></div><section className="student-course-grid">{visible.map((course) => <Link className="student-course-card" href={`/student/cours/${course.id}`} key={course.id}><div className={`student-course-visual ${course.color}`}>{course.icon}</div><div className="student-course-content"><span className="student-course-tag">{labels[course.category]}</span><h3>{course.title}</h3><p>{course.objective}</p><div className="student-course-meter"><i style={{ width: `${course.progress}%` }} /></div><div className="student-course-bottom"><small>{course.progress}% {fr ? "terminé" : "complete"}</small><span>{fr ? "Choisir un travail" : "Choose an assignment"} →</span></div></div></Link>)}</section></section></main>;
}
