"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { localizeCourses, type CourseCategory } from "@/src/domain/course-catalog";
import StudentNav from "@/components/student/StudentNav";

const labels: Record<string, string> = { Mathematiques: "Mathématiques", Francais: "Français", Anglais: "English", Sciences: "Sciences", Arabe: "Arabe", Coran: "Coran" };

export default function StudentCoursesPage() {
  const [filter, setFilter] = useState<"Toutes" | CourseCategory>("Toutes");
  const [query, setQuery] = useState("");
  const [locale, setLocale] = useState<"fr" | "en">("fr");
  const visible = useMemo(() => localizeCourses(locale).filter((course) => (filter === "Toutes" || course.category === filter) && `${course.title} ${course.objective}`.toLowerCase().includes(query.toLowerCase())), [filter, query, locale]);
  return <main className="student-v2-shell min-h-screen bg-[#f3faf5]"><StudentNav active="courses" locale={locale} /><section className="student-v2-main"><header className="student-v2-top"><div><p className="student-v2-kicker">{locale === "fr" ? "Espace élève" : "Student space"}</p><h1>{locale === "fr" ? "Mes cours" : "My courses"}</h1></div><button className="student-v2-locale" onClick={() => setLocale(locale === "fr" ? "en" : "fr")}>{locale === "fr" ? "EN" : "FR"}</button></header><section className="student-course-intro"><div><p className="student-v2-kicker">{locale === "fr" ? "Choisis ton prochain défi" : "Choose your next challenge"}</p><h2>{locale === "fr" ? "Apprendre peut changer de forme." : "Learning can take many forms."}</h2><p>{locale === "fr" ? "Mathématiques, français, anglais, sciences, arabe ou Coran : avance à ton rythme." : "Math, French, English, science, Arabic or Quran: move at your own pace."}</p></div><div className="student-course-orbit"><span>∑</span><span>ABC</span><span>⌁</span><span>☽</span></div></section><div className="student-course-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={locale === "fr" ? "Rechercher un cours…" : "Search a course…"} aria-label={locale === "fr" ? "Rechercher un cours" : "Search a course"} /><div className="student-course-filters"><button className={filter === "Toutes" ? "active" : ""} onClick={() => setFilter("Toutes")}>{locale === "fr" ? "Tout" : "All"}</button>{(["Mathematiques", "Francais", "Anglais", "Sciences", "Arabe", "Coran"] as CourseCategory[]).map((category) => <button key={category} className={filter === category ? "active" : ""} onClick={() => setFilter(category)}>{labels[category]}</button>)}</div></div><section className="student-course-grid">{visible.map((course) => <article className="student-course-card" key={course.id}><div className={`student-course-visual ${course.color}`}>{course.icon}</div><div className="student-course-content"><span className="student-course-tag">{labels[course.category]}</span><h3>{course.title}</h3><p>{course.objective}</p><div className="student-course-meter"><i style={{ width: `${course.progress}%` }} /></div><div className="student-course-bottom"><small>{course.progress}% {locale === "fr" ? "terminé" : "complete"}</small><Link href={`/student/cours/${course.id}`}>{locale === "fr" ? "Ouvrir" : "Open"} →</Link></div></div></article>)}</section></section></main>;
}
