"use client";

import Link from "next/link";
import { useState } from "react";

const people = ["Lina", "Yusuf", "Meryem", "Adam", "Toi"];

export default function StudentLivePage() {
  const [locale, setLocale] = useState<"fr" | "en">("fr");
  const [stage, setStage] = useState<"lobby" | "activity" | "ticket">("lobby");
  const [answer, setAnswer] = useState<string | null>(null);
  const [help, setHelp] = useState(false);
  const fr = locale === "fr";
  return <main className="live-shell student-live-shell">
    <aside className="student-v2-sidebar live-sidebar"><Link href="/" className="student-v2-logo"><img src="/ui/logo-madrasa-quebec.png" alt="Madrasa Québec Network" /></Link><span className="student-v2-label">{fr ? "Ma classe" : "My class"}</span><Link className="student-v2-nav active" href="/student/live/atelier-ecosystemes">◉ <span>{fr ? "Classe en direct" : "Live class"}</span></Link><Link className="student-v2-nav" href="/student">⌂ <span>{fr ? "Aujourd’hui" : "Today"}</span></Link><Link className="student-v2-nav" href="/student/progression">✦ <span>{fr ? "Ma progression" : "My progress"}</span></Link><div className="student-v2-sidebar-help">{fr ? "Une question ?" : "Need help?"}<br /><small>{fr ? "Demande de l’aide sans quitter la classe." : "Ask for help without leaving class."}</small></div></aside>
    <section className="live-main"><header className="live-topbar"><div><p className="student-v2-kicker">{fr ? "Classe en direct · Sciences" : "Live class · Science"}</p><h1>{fr ? "Les écosystèmes" : "Ecosystems"}</h1></div><div className="live-top-actions"><span className="live-status"><i /> {fr ? "En direct" : "Live"}</span><button className="student-v2-locale" onClick={() => setLocale(fr ? "en" : "fr")}>{fr ? "EN" : "FR"}</button></div></header>
      <div className="live-progress"><span className={stage === "lobby" ? "current" : "done"}>01 <b>{fr ? "Accueil" : "Lobby"}</b></span><span className={stage === "activity" ? "current" : stage === "ticket" ? "done" : ""}>02 <b>{fr ? "Activité" : "Activity"}</b></span><span className={stage === "ticket" ? "current" : ""}>03 <b>{fr ? "Ticket de sortie" : "Exit ticket"}</b></span></div>
      {stage === "lobby" && <section className="live-hero-card"><div><span className="live-eyebrow">{fr ? "Bienvenue dans la classe" : "Welcome to class"}</span><h2>{fr ? "On apprend ensemble, une idée à la fois." : "We learn together, one idea at a time."}</h2><p>{fr ? "Présente-toi, écoute les autres et prépare-toi à résoudre un défi sur les abeilles." : "Introduce yourself, listen to others and get ready to solve a challenge about bees."}</p><button className="live-primary" onClick={() => setStage("activity")}>{fr ? "Entrer dans la classe" : "Enter class"} →</button></div><div className="live-lobby-illustration"><span>✦</span><strong>5</strong><small>{fr ? "élèves présents" : "students here"}</small></div></section>}
      {stage === "activity" && <section className="live-content-grid"><div className="live-activity-card"><div className="live-card-top"><span className="live-eyebrow">{fr ? "Défi partagé" : "Shared challenge"}</span><span className="live-turn">{fr ? "Tour de Lina" : "Lina’s turn"}</span></div><h2>{fr ? "Que se passe-t-il si les abeilles disparaissent ?" : "What happens if bees disappear?"}</h2><p>{fr ? "Choisis une conséquence et explique ton raisonnement au groupe." : "Choose one consequence and explain your reasoning to the group."}</p><div className="live-choice-grid">{[fr ? "Moins de fruits" : "Fewer fruits", fr ? "Plus de pluie" : "More rain", fr ? "Des océans salés" : "Saltier oceans"].map((item) => <button key={item} className={answer === item ? "selected" : ""} onClick={() => setAnswer(item)}>{item}<span>→</span></button>)}</div>{answer && <div className="live-answer-note">✓ {fr ? "Ton idée est enregistrée. Prépare une explication en une phrase." : "Your idea is saved. Prepare a one-sentence explanation."}</div>}<button className="live-primary" onClick={() => setStage("ticket")}>{fr ? "Passer au ticket de sortie" : "Go to exit ticket"} →</button></div><aside className="live-people-card"><div className="live-card-top"><h3>{fr ? "Dans la classe" : "In class"}</h3><span>{people.length} / 6</span></div><div className="live-people-list">{people.map((person, i) => <div key={person}><span className={`live-avatar avatar-${i}`}>{person[0]}</span><b>{person}</b><small>{i === 0 ? (fr ? "parle" : "speaking") : i === 4 ? (fr ? "toi" : "you") : (fr ? "présent" : "here")}</small></div>)}</div><button className="live-help-button" onClick={() => setHelp(true)}>✋ {fr ? "Demander de l’aide" : "Ask for help"}</button></aside></section>}
      {stage === "ticket" && <section className="live-ticket-card"><span className="live-eyebrow">{fr ? "Dernière minute" : "Last minute"}</span><h2>{fr ? "Une idée à garder avant de partir ?" : "One idea to keep before you go?"}</h2><p>{fr ? "Écris une chose que tu as comprise et une question que tu gardes." : "Write one thing you understood and one question you still have."}</p><label>{fr ? "J’ai compris que…" : "I learned that…"}<textarea placeholder={fr ? "Les abeilles…" : "Bees…"} /></label><label>{fr ? "Je me demande encore…" : "I still wonder…"}<textarea placeholder={fr ? "Ma question…" : "My question…"} /></label><button className="live-primary" onClick={() => setStage("lobby")}>{fr ? "Envoyer au tuteur" : "Send to tutor"} ✓</button></section>}
      <div className="live-mini-game"><div><span className="live-eyebrow">{fr ? "Mini-jeu · 2 min" : "Mini-game · 2 min"}</span><h3>{fr ? "Relie la cause à l’effet" : "Match cause and effect"}</h3></div><div className="live-game-pills"><button>🌼 {fr ? "Pollinisation" : "Pollination"}</button><button>🍎 {fr ? "Fruits" : "Fruit"}</button><span>+20 ✦</span></div></div>
      {help && <div className="live-toast" role="status">{fr ? "Le tuteur arrive dans un instant. Continue à observer l’activité." : "The tutor will be with you shortly. Keep observing the activity."}<button onClick={() => setHelp(false)}>×</button></div>}
    </section>
  </main>;
}
