"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuebecLocale } from "@/components/quebec/quebec-locale";
import { getQuebecDictionary } from "@/components/quebec/quebec-dictionary";
import { QuebecSidebar } from "@/components/quebec/QuebecSidebar";

const sections = {
  situation: { icon: "⌂", fr: { title: "Votre situation", intro: "Répondez à trois questions pour que les dates du parcours correspondent à votre famille.", points: ["Indiquer si votre enfant a déjà quitté l’école.", "Choisir l’année scolaire concernée.", "Ajouter la vraie date de mise en œuvre du projet.", "Choisir le mode d’évaluation envisagé."], action: "Modifier ma situation", anchor: "quebec-situation" }, en: { title: "Your situation", intro: "Answer three questions so the path dates match your family.", points: ["Tell us whether your child has left school.", "Choose the school year.", "Add the actual project start date.", "Choose a possible evaluation method."], action: "Edit my situation", anchor: "quebec-situation" } },
  "avis-declaration": { icon: "↗", fr: { title: "Avis de déclaration", intro: "Préparez le même avis pour le ministère et votre centre de services scolaire, puis transmettez vous-même chaque version.", points: ["Rassembler les informations de l’enfant et des deux parents.", "Vérifier l’adresse et le code permanent.", "Télécharger les deux brouillons séparés.", "Déposer le premier dans l’espace sécurisé du ministère et suivre la voie indiquée par le CSS."], action: "Ouvrir le générateur d’avis", anchor: "quebec-avis" }, en: { title: "Notice of intent", intro: "Prepare one notice for the ministry and your school service centre, then send each version yourself.", points: ["Gather the child and both parents’ information.", "Check the address and permanent code.", "Download the two separate drafts.", "Submit the ministry copy in the secure space and follow your CSS instructions."], action: "Open notice generator", anchor: "quebec-avis" } },
  suivi: { icon: "◷", fr: { title: "Suivi annuel", intro: "Le suivi, l’état de situation et le bilan de mi-parcours se rencontrent au même moment, mais restent trois obligations distinctes.", points: ["Préparer un résumé de la progression de l’enfant.", "Réserver ou confirmer la rencontre de suivi.", "Noter les dates de l’état de situation et du bilan.", "Conserver les preuves et décisions dans le portfolio familial."], action: "Voir le suivi annuel", anchor: "quebec-suivi" }, en: { title: "Annual follow-up", intro: "The follow-up meeting, situation report and mid-year report happen in the same period but remain three distinct requirements.", points: ["Prepare a short learning-progress summary.", "Book or confirm the follow-up meeting.", "Track the situation and mid-year report dates.", "Keep evidence and decisions in the family portfolio."], action: "View annual follow-up", anchor: "quebec-suivi" } },
  obligations: { icon: "✓", fr: { title: "Toutes les obligations", intro: "Une liste chronologique explique quoi faire, pour qui, quand et sur quelle règle la date est fondée.", points: ["Lire la date calculée et son niveau d’urgence.", "Ouvrir la source officielle associée.", "Marquer l’étape comme brouillon, envoyée ou reçue.", "Saisir une date réelle lorsque le moteur utilise une estimation."], action: "Ouvrir la timeline", anchor: "quebec-timeline" }, en: { title: "All requirements", intro: "A chronological list explains what to do, for whom, when and which rule supports each date.", points: ["Read the calculated date and urgency.", "Open the linked official source.", "Mark the step as draft, sent or received.", "Enter an actual date when the engine uses an estimate."], action: "Open timeline", anchor: "quebec-timeline" } },
  projet: { icon: "✎", fr: { title: "Projet d’apprentissage", intro: "Décrivez votre approche, vos activités et les matières prévues sans perdre de vue les attentes du Québec.", points: ["Décrire l’approche éducative choisie.", "Lister les activités et ressources utilisées.", "Décrire les apprentissages en langue, mathématique, science et univers social.", "Enregistrer un brouillon puis le relire avec un adulte compétent."], action: "Modifier le projet", anchor: "quebec-projet" }, en: { title: "Learning project", intro: "Describe your approach, activities and subjects while keeping Quebec expectations in view.", points: ["Describe the educational approach.", "List activities and resources.", "Describe learning in language, mathematics, science and social studies.", "Save a draft and review it with a qualified adult."], action: "Edit learning project", anchor: "quebec-projet" } },
  export: { icon: "↓", fr: { title: "Exporter le parcours", intro: "Créez un brouillon lisible et un fichier JSON versionné. Rien n’est envoyé automatiquement.", points: ["Relire toutes les informations avant l’export.", "Vérifier le millésime du catalogue de règles.", "Télécharger le fichier et le conserver dans un endroit sûr.", "Transmettre vous-même les documents par le canal officiel."], action: "Ouvrir l’export", anchor: "quebec-export" }, en: { title: "Export the path", intro: "Create a readable draft and a versioned JSON file. Nothing is sent automatically.", points: ["Review every field before exporting.", "Check the rules catalogue version.", "Download and store the file securely.", "Send documents yourself through the official channel."], action: "Open export", anchor: "quebec-export" } },
} as const;

export default function QuebecSectionPage() {
  const params = useParams<{ section: string }>();
  const { locale, setLocale } = useQuebecLocale();
  const dictionary = getQuebecDictionary(locale);
  const section = sections[params.section as keyof typeof sections] ?? sections.obligations;
  const copy = section[locale];
  return <main className="app-shell"><QuebecSidebar dictionary={dictionary} /><section className="workspace quebec-detail-workspace"><div className="quebec-toolbar"><Link className="quebec-back-link" href="/parent/parcours-quebec">← {locale === "fr" ? "Retour au parcours" : "Back to path"}</Link><div className="real-language-switch"><button className={locale === "fr" ? "active" : ""} onClick={() => setLocale("fr")} aria-pressed={locale === "fr"}>Français</button><button className={locale === "en" ? "active" : ""} onClick={() => setLocale("en")} aria-pressed={locale === "en"}>English</button></div></div><div className="quebec-detail-hero"><span className="quebec-detail-number">{section.icon}</span><div><div className="eyebrow">{locale === "fr" ? "Parcours Québec · détail" : "Quebec path · detail"}</div><h1>{copy.title}</h1><p>{copy.intro}</p></div></div><div className="quebec-detail-layout"><article className="quebec-detail-card"><span className="eyebrow">{locale === "fr" ? "Ce que vous allez faire" : "What you will do"}</span><h2>{locale === "fr" ? "Une étape claire, sans deviner" : "One clear step at a time"}</h2><ol>{copy.points.map((point) => <li key={point}><span>✓</span>{point}</li>)}</ol><Link className="button button-primary" href={`/parent/parcours-quebec#${copy.anchor}`}>{copy.action} →</Link></article><aside className="quebec-detail-note"><span>✦</span><h2>{locale === "fr" ? "À retenir" : "Keep in mind"}</h2><p>{locale === "fr" ? "Les dates affichées sont des repères. Le parent reste responsable de vérifier la source et de transmettre ses documents lui-même." : "Displayed dates are guidance. Parents remain responsible for checking the source and sending documents themselves."}</p><a href="https://www.quebec.ca/education/prescolaire-primaire-et-secondaire/programmes-formations-evaluation/enseignement-maison" target="_blank" rel="noreferrer">{locale === "fr" ? "Lire la source officielle ↗" : "Read the official source ↗"}</a></aside></div><div className="quebec-detail-next"><span>{locale === "fr" ? "Retour au tableau de bord" : "Back to overview"}</span><Link href="/parent/parcours-quebec">{locale === "fr" ? "Voir toutes les étapes" : "See all steps"} →</Link></div></section></main>;
}
